name: golintr
author: norwd
description: "Lint your code using golint"

branding:
  icon: check-circle
  color: green

inputs:
  path:
    description: 'Path used by golint command'
    required: false
    default: './...'

outputs:
  errors:
    description: 'The golint output if the command fail'
    value: ${{ steps.golint.outputs.golint-output }}

runs:
  using: composite
  steps:
    - name: "Install `golint`"
      id: install
      shell: bash
      run: go install golang.org/x/lint/golint@latest

    - name: "Run `golint`"
      id: golint
      env:
        GOLINT_PATH: ${{ inputs.path }}
      shell: bash
      run: |
        echo "golint-output<<EOF" >> "${GITHUB_OUTPUT}"
        ~/go/bin/golint -set_exit_status "${GOLINT_PATH}" >> "${GITHUB_OUTPUT}" || true
        echo "EOF" >> "${GITHUB_OUTPUT}"

    - name: "Report Errors (if any)"
      if: steps.golint.outputs.golint-output != ''
      shell: bash
      run: exit 1
