name: golintr
author: norwd
description: "Lint your code using golint"

branding:
  icon: check-circle
  color: green

inputs:
  path:
    description: 'Path used by golint command'
    required: false
    default: './...'

outputs:
  errors:
    description: 'The golint output if the command fail'
    value: ${{ steps.golint.outputs.errors }}

runs:
  using: composite
  steps:
    - name: "Run `golint`"
      id: golint
      env:
        GOLINT_PATH: ${{ inputs.path }}
      shell: bash
      run: |
        if ! GOLINT_OUTPUT="$(golint -set_exit_status "${GOLINT_PATH}")"
        then
          echo "::error::${GITHUB_OUTPUT}"

          if [ -z "${GITHUB_OUTPUT}" ]
          then
            echo "::set-output name=errors::${GOLINT_OUTPUT}"
          else
            echo "errors=${GOLINT_OUTPUT}" >> "${GITHUB_OUTPUT}"
          fi

          exit 1
        fi
