name: golintr
author: norwd
description: "Lint your code using golint"

branding:
  icon: check-circle
  color: green

inputs:
  path:
    description: 'Path used by golint command'
    required: false
    default: './...'

outputs:
  errors:
    description: 'The golint output if the command fail'
    value: ${{ steps.golint.outputs.errors }}

runs:
  runs:
  using: composite
  steps:
    - name: "Run `golint`"
      id: golint
      shel: bash
      run: |
        cd $GITHUB_WORKSPACE

        GOLINT_OUTPUT="$(golint -set_exit_status ${{ inputs.path }})"
        if [ $? -ne 0 ]; then
          echo "${GOLINT_OUTPUT}"
          exit 1
        fi

        if [ -z "${GITHUB_OUTPUT}" ]; then
          echo "::set-output name=errors::Golint step succeed"
        else
          echo "errors=Golint step succeed" >> "${GITHUB_OUTPUT}"
        fi
