name: golintr
author: norwd
description: "Lint your code using golint"

branding:
  icon: check-circle
  color: green

inputs:
  path:
    description: 'Path used by golint command'
    required: false
    default: './...'

outputs:
  errors:
    description: 'The golint output if the command fail'
    value: ${{ steps.golint.outputs.golint-output }}

runs:
  using: composite
  steps:
    - name: "Install `golint`"
      id: install
      shell: bash
      run: go install golang.org/x/lint/golint@latest

    - name: "Run `golint`"
      id: golint
      shell: bash
      run: |
        {
          echo "golint-output<<EOF"
          ~/go/bin/golint -set_exit_status "${GOLINT_PATH}" || true
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
      env:
        GOLINT_PATH: ${{ inputs.path }}

    - name: "Report Errors (if any)"
      if: steps.golint.outputs.golint-output != ''
      shell: bash
      run: exit 1
