---

name: "Self Test"

on:
  push:

jobs:
  golintr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Run Golint
        id: golintr
        uses: norwd/golintr@main
        with:
          path: .github/test/...

      - name: Display Errors
        if: failure() || steps.golintr.outputs.errors != ''
        shell: bash
        env:
          GOLINTR_ERRORS: ${{ steps.golintr.outputs.errors }}
        run: |
          echo "$GOLINTR_ERRORS" | awk -F : '{ file=$1; $1=""; line=$2; $2=""; title="Go Lint Error"; $3=""; print "file=" file ",line=" line ",title=" title "::" $0 }'
